
//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by a tool. 
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------

namespace Catel.Data
{
	using System;

	public static partial class BoxingCache
	{
        /// <summary>
        /// Converts the specified value into a cached boxed value in case of value type to decrease memory pressure after serialization.
        /// </summary>
        /// <param name="value">The value.</param>
        /// <returns>An object representing the value.</returns>
        public static object GetBoxedValue(object value)
        {
            object objectValue = value;

            if (value != null)
            {
                var valueType = value.GetType();
                if (valueType.IsValueType)
                {
					if (false)
					{
						// Dummy code node
					}
                    else if (valueType == typeof(Boolean))
                    {
                        objectValue = BoxingCache<Boolean>.Default.GetBoxedValue((Boolean)value);
                    }
                    else if (valueType == typeof(Char))
                    {
                        objectValue = BoxingCache<Char>.Default.GetBoxedValue((Char)value);
                    }
                    else if (valueType == typeof(SByte))
                    {
                        objectValue = BoxingCache<SByte>.Default.GetBoxedValue((SByte)value);
                    }
                    else if (valueType == typeof(Byte))
                    {
                        objectValue = BoxingCache<Byte>.Default.GetBoxedValue((Byte)value);
                    }
                    else if (valueType == typeof(Int16))
                    {
                        objectValue = BoxingCache<Int16>.Default.GetBoxedValue((Int16)value);
                    }
                    else if (valueType == typeof(UInt16))
                    {
                        objectValue = BoxingCache<UInt16>.Default.GetBoxedValue((UInt16)value);
                    }
                    else if (valueType == typeof(Int32))
                    {
                        objectValue = BoxingCache<Int32>.Default.GetBoxedValue((Int32)value);
                    }
                    else if (valueType == typeof(UInt32))
                    {
                        objectValue = BoxingCache<UInt32>.Default.GetBoxedValue((UInt32)value);
                    }
                    else if (valueType == typeof(Int64))
                    {
                        objectValue = BoxingCache<Int64>.Default.GetBoxedValue((Int64)value);
                    }
                    else if (valueType == typeof(UInt64))
                    {
                        objectValue = BoxingCache<UInt64>.Default.GetBoxedValue((UInt64)value);
                    }
                    else if (valueType == typeof(Single))
                    {
                        objectValue = BoxingCache<Single>.Default.GetBoxedValue((Single)value);
                    }
                    else if (valueType == typeof(Double))
                    {
                        objectValue = BoxingCache<Double>.Default.GetBoxedValue((Double)value);
                    }
                    else if (valueType == typeof(Decimal))
                    {
                        objectValue = BoxingCache<Decimal>.Default.GetBoxedValue((Decimal)value);
                    }
                    else if (valueType == typeof(DateTime))
                    {
                        objectValue = BoxingCache<DateTime>.Default.GetBoxedValue((DateTime)value);
                    }
                    else if (valueType == typeof(String))
                    {
                        objectValue = BoxingCache<String>.Default.GetBoxedValue((String)value);
                    }
                }
            }

            return objectValue;
        }
	}
}