//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catel.Test.EntityFramework5.DbContextTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbContextProduct
    {
        public DbContextProduct()
        {
            this.DbContextOrders = new HashSet<DbContextOrder>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<DbContextOrder> DbContextOrders { get; set; }
    }
}
