//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("TestObjectContext", "FK_OrderCustomer", "ObjectContextCustomer", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Catel.Test.EntityFramework5.ObjectContextTest.ObjectContextCustomer), "ObjectContextOrder", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Catel.Test.EntityFramework5.ObjectContextTest.ObjectContextOrder), true)]
[assembly: EdmRelationshipAttribute("TestObjectContext", "FK_ProductOrder", "ObjectContextProduct", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Catel.Test.EntityFramework5.ObjectContextTest.ObjectContextProduct), "ObjectContextOrder", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Catel.Test.EntityFramework5.ObjectContextTest.ObjectContextOrder), true)]

#endregion

namespace Catel.Test.EntityFramework5.ObjectContextTest
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class TestObjectContextContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new TestObjectContextContainer object using the connection string found in the 'TestObjectContextContainer' section of the application configuration file.
        /// </summary>
        public TestObjectContextContainer() : base("name=TestObjectContextContainer", "TestObjectContextContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TestObjectContextContainer object.
        /// </summary>
        public TestObjectContextContainer(string connectionString) : base(connectionString, "TestObjectContextContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TestObjectContextContainer object.
        /// </summary>
        public TestObjectContextContainer(EntityConnection connection) : base(connection, "TestObjectContextContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ObjectContextCustomer> ObjectContextCustomers
        {
            get
            {
                if ((_ObjectContextCustomers == null))
                {
                    _ObjectContextCustomers = base.CreateObjectSet<ObjectContextCustomer>("ObjectContextCustomers");
                }
                return _ObjectContextCustomers;
            }
        }
        private ObjectSet<ObjectContextCustomer> _ObjectContextCustomers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ObjectContextOrder> ObjectContextOrders
        {
            get
            {
                if ((_ObjectContextOrders == null))
                {
                    _ObjectContextOrders = base.CreateObjectSet<ObjectContextOrder>("ObjectContextOrders");
                }
                return _ObjectContextOrders;
            }
        }
        private ObjectSet<ObjectContextOrder> _ObjectContextOrders;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ObjectContextProduct> ObjectContextProducts
        {
            get
            {
                if ((_ObjectContextProducts == null))
                {
                    _ObjectContextProducts = base.CreateObjectSet<ObjectContextProduct>("ObjectContextProducts");
                }
                return _ObjectContextProducts;
            }
        }
        private ObjectSet<ObjectContextProduct> _ObjectContextProducts;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ObjectContextCustomers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToObjectContextCustomers(ObjectContextCustomer objectContextCustomer)
        {
            base.AddObject("ObjectContextCustomers", objectContextCustomer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ObjectContextOrders EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToObjectContextOrders(ObjectContextOrder objectContextOrder)
        {
            base.AddObject("ObjectContextOrders", objectContextOrder);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ObjectContextProducts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToObjectContextProducts(ObjectContextProduct objectContextProduct)
        {
            base.AddObject("ObjectContextProducts", objectContextProduct);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TestObjectContext", Name="ObjectContextCustomer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ObjectContextCustomer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ObjectContextCustomer object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="street">Initial value of the Street property.</param>
        /// <param name="country">Initial value of the Country property.</param>
        public static ObjectContextCustomer CreateObjectContextCustomer(global::System.Int32 id, global::System.String name, global::System.String street, global::System.String country)
        {
            ObjectContextCustomer objectContextCustomer = new ObjectContextCustomer();
            objectContextCustomer.Id = id;
            objectContextCustomer.Name = name;
            objectContextCustomer.Street = street;
            objectContextCustomer.Country = country;
            return objectContextCustomer;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Street
        {
            get
            {
                return _Street;
            }
            set
            {
                OnStreetChanging(value);
                ReportPropertyChanging("Street");
                _Street = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Street");
                OnStreetChanged();
            }
        }
        private global::System.String _Street;
        partial void OnStreetChanging(global::System.String value);
        partial void OnStreetChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Country
        {
            get
            {
                return _Country;
            }
            set
            {
                OnCountryChanging(value);
                ReportPropertyChanging("Country");
                _Country = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Country");
                OnCountryChanged();
            }
        }
        private global::System.String _Country;
        partial void OnCountryChanging(global::System.String value);
        partial void OnCountryChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TestObjectContext", "FK_OrderCustomer", "ObjectContextOrder")]
        public EntityCollection<ObjectContextOrder> ObjectContextOrders
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ObjectContextOrder>("TestObjectContext.FK_OrderCustomer", "ObjectContextOrder");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ObjectContextOrder>("TestObjectContext.FK_OrderCustomer", "ObjectContextOrder", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TestObjectContext", Name="ObjectContextOrder")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ObjectContextOrder : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ObjectContextOrder object.
        /// </summary>
        /// <param name="productId">Initial value of the ProductId property.</param>
        /// <param name="customerId">Initial value of the CustomerId property.</param>
        /// <param name="orderCreated">Initial value of the OrderCreated property.</param>
        /// <param name="amount">Initial value of the Amount property.</param>
        /// <param name="product_Id">Initial value of the Product_Id property.</param>
        /// <param name="customer_Id">Initial value of the Customer_Id property.</param>
        public static ObjectContextOrder CreateObjectContextOrder(global::System.Int32 productId, global::System.Int32 customerId, global::System.DateTime orderCreated, global::System.Int32 amount, global::System.Int32 product_Id, global::System.Int32 customer_Id)
        {
            ObjectContextOrder objectContextOrder = new ObjectContextOrder();
            objectContextOrder.ProductId = productId;
            objectContextOrder.CustomerId = customerId;
            objectContextOrder.OrderCreated = orderCreated;
            objectContextOrder.Amount = amount;
            objectContextOrder.Product_Id = product_Id;
            objectContextOrder.Customer_Id = customer_Id;
            return objectContextOrder;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProductId
        {
            get
            {
                return _ProductId;
            }
            set
            {
                if (_ProductId != value)
                {
                    OnProductIdChanging(value);
                    ReportPropertyChanging("ProductId");
                    _ProductId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ProductId");
                    OnProductIdChanged();
                }
            }
        }
        private global::System.Int32 _ProductId;
        partial void OnProductIdChanging(global::System.Int32 value);
        partial void OnProductIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CustomerId
        {
            get
            {
                return _CustomerId;
            }
            set
            {
                if (_CustomerId != value)
                {
                    OnCustomerIdChanging(value);
                    ReportPropertyChanging("CustomerId");
                    _CustomerId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CustomerId");
                    OnCustomerIdChanged();
                }
            }
        }
        private global::System.Int32 _CustomerId;
        partial void OnCustomerIdChanging(global::System.Int32 value);
        partial void OnCustomerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime OrderCreated
        {
            get
            {
                return _OrderCreated;
            }
            set
            {
                OnOrderCreatedChanging(value);
                ReportPropertyChanging("OrderCreated");
                _OrderCreated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrderCreated");
                OnOrderCreatedChanged();
            }
        }
        private global::System.DateTime _OrderCreated;
        partial void OnOrderCreatedChanging(global::System.DateTime value);
        partial void OnOrderCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Amount
        {
            get
            {
                return _Amount;
            }
            set
            {
                OnAmountChanging(value);
                ReportPropertyChanging("Amount");
                _Amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Amount");
                OnAmountChanged();
            }
        }
        private global::System.Int32 _Amount;
        partial void OnAmountChanging(global::System.Int32 value);
        partial void OnAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Product_Id
        {
            get
            {
                return _Product_Id;
            }
            set
            {
                OnProduct_IdChanging(value);
                ReportPropertyChanging("Product_Id");
                _Product_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Product_Id");
                OnProduct_IdChanged();
            }
        }
        private global::System.Int32 _Product_Id;
        partial void OnProduct_IdChanging(global::System.Int32 value);
        partial void OnProduct_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Customer_Id
        {
            get
            {
                return _Customer_Id;
            }
            set
            {
                OnCustomer_IdChanging(value);
                ReportPropertyChanging("Customer_Id");
                _Customer_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Customer_Id");
                OnCustomer_IdChanged();
            }
        }
        private global::System.Int32 _Customer_Id;
        partial void OnCustomer_IdChanging(global::System.Int32 value);
        partial void OnCustomer_IdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TestObjectContext", "FK_OrderCustomer", "ObjectContextCustomer")]
        public ObjectContextCustomer ObjectContextCustomer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ObjectContextCustomer>("TestObjectContext.FK_OrderCustomer", "ObjectContextCustomer").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ObjectContextCustomer>("TestObjectContext.FK_OrderCustomer", "ObjectContextCustomer").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ObjectContextCustomer> ObjectContextCustomerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ObjectContextCustomer>("TestObjectContext.FK_OrderCustomer", "ObjectContextCustomer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ObjectContextCustomer>("TestObjectContext.FK_OrderCustomer", "ObjectContextCustomer", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TestObjectContext", "FK_ProductOrder", "ObjectContextProduct")]
        public ObjectContextProduct ObjectContextProduct
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ObjectContextProduct>("TestObjectContext.FK_ProductOrder", "ObjectContextProduct").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ObjectContextProduct>("TestObjectContext.FK_ProductOrder", "ObjectContextProduct").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ObjectContextProduct> ObjectContextProductReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ObjectContextProduct>("TestObjectContext.FK_ProductOrder", "ObjectContextProduct");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ObjectContextProduct>("TestObjectContext.FK_ProductOrder", "ObjectContextProduct", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TestObjectContext", Name="ObjectContextProduct")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ObjectContextProduct : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ObjectContextProduct object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static ObjectContextProduct CreateObjectContextProduct(global::System.Int32 id, global::System.String name)
        {
            ObjectContextProduct objectContextProduct = new ObjectContextProduct();
            objectContextProduct.Id = id;
            objectContextProduct.Name = name;
            return objectContextProduct;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TestObjectContext", "FK_ProductOrder", "ObjectContextOrder")]
        public EntityCollection<ObjectContextOrder> ObjectContextOrders
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ObjectContextOrder>("TestObjectContext.FK_ProductOrder", "ObjectContextOrder");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ObjectContextOrder>("TestObjectContext.FK_ProductOrder", "ObjectContextOrder", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
