//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by a tool. 
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------

namespace Catel.Reflection
{
    using System;
    using Catel.Data;

	public partial class FastMemberInvoker<TEntity>
	{
        public bool SetFieldValue<TValue>(object entity, string fieldName, TValue value)
        {
            if (!typeof(TValue).IsValueTypeEx())
            {
                return SetFieldValue((TEntity)entity, fieldName, (object)value);
            }

            if (typeof(TValue) == typeof(Boolean))
            {
                var finalValue = Convert.ToBoolean(value);
                return SetFieldValue((TEntity)entity, fieldName, finalValue);
            }

            if (typeof(TValue) == typeof(Char))
            {
                var finalValue = Convert.ToChar(value);
                return SetFieldValue((TEntity)entity, fieldName, finalValue);
            }

            if (typeof(TValue) == typeof(SByte))
            {
                var finalValue = Convert.ToSByte(value);
                return SetFieldValue((TEntity)entity, fieldName, finalValue);
            }

            if (typeof(TValue) == typeof(Byte))
            {
                var finalValue = Convert.ToByte(value);
                return SetFieldValue((TEntity)entity, fieldName, finalValue);
            }

            if (typeof(TValue) == typeof(Int16))
            {
                var finalValue = Convert.ToInt16(value);
                return SetFieldValue((TEntity)entity, fieldName, finalValue);
            }

            if (typeof(TValue) == typeof(UInt16))
            {
                var finalValue = Convert.ToUInt16(value);
                return SetFieldValue((TEntity)entity, fieldName, finalValue);
            }

            if (typeof(TValue) == typeof(Int32))
            {
                var finalValue = Convert.ToInt32(value);
                return SetFieldValue((TEntity)entity, fieldName, finalValue);
            }

            if (typeof(TValue) == typeof(UInt32))
            {
                var finalValue = Convert.ToUInt32(value);
                return SetFieldValue((TEntity)entity, fieldName, finalValue);
            }

            if (typeof(TValue) == typeof(Int64))
            {
                var finalValue = Convert.ToInt64(value);
                return SetFieldValue((TEntity)entity, fieldName, finalValue);
            }

            if (typeof(TValue) == typeof(UInt64))
            {
                var finalValue = Convert.ToUInt64(value);
                return SetFieldValue((TEntity)entity, fieldName, finalValue);
            }

            if (typeof(TValue) == typeof(Single))
            {
                var finalValue = Convert.ToSingle(value);
                return SetFieldValue((TEntity)entity, fieldName, finalValue);
            }

            if (typeof(TValue) == typeof(Double))
            {
                var finalValue = Convert.ToDouble(value);
                return SetFieldValue((TEntity)entity, fieldName, finalValue);
            }

            if (typeof(TValue) == typeof(Decimal))
            {
                var finalValue = Convert.ToDecimal(value);
                return SetFieldValue((TEntity)entity, fieldName, finalValue);
            }

            if (typeof(TValue) == typeof(DateTime))
            {
                var finalValue = Convert.ToDateTime(value);
                return SetFieldValue((TEntity)entity, fieldName, finalValue);
            }

            if (typeof(TValue) == typeof(String))
            {
                var finalValue = Convert.ToString(value);
                return SetFieldValue((TEntity)entity, fieldName, finalValue);
            }

            return false;
        }

        public bool SetFieldValue(TEntity entity, string fieldName, Object value)
        {
            var setter = GetObjectFieldSetter(fieldName);
            if (setter != null)
            {
                setter(entity, value);
                return true;
            }

            return false;
        }

        public bool SetFieldValue(TEntity entity, string fieldName, Boolean value)
        {
            var setter = GetBooleanFieldSetter(fieldName);
            if (setter != null)
            {
                setter(entity, value);
                return true;
            }

            return false;
        }

        public bool SetFieldValue(TEntity entity, string fieldName, Char value)
        {
            var setter = GetCharFieldSetter(fieldName);
            if (setter != null)
            {
                setter(entity, value);
                return true;
            }

            return false;
        }

        public bool SetFieldValue(TEntity entity, string fieldName, SByte value)
        {
            var setter = GetSByteFieldSetter(fieldName);
            if (setter != null)
            {
                setter(entity, value);
                return true;
            }

            return false;
        }

        public bool SetFieldValue(TEntity entity, string fieldName, Byte value)
        {
            var setter = GetByteFieldSetter(fieldName);
            if (setter != null)
            {
                setter(entity, value);
                return true;
            }

            return false;
        }

        public bool SetFieldValue(TEntity entity, string fieldName, Int16 value)
        {
            var setter = GetInt16FieldSetter(fieldName);
            if (setter != null)
            {
                setter(entity, value);
                return true;
            }

            return false;
        }

        public bool SetFieldValue(TEntity entity, string fieldName, UInt16 value)
        {
            var setter = GetUInt16FieldSetter(fieldName);
            if (setter != null)
            {
                setter(entity, value);
                return true;
            }

            return false;
        }

        public bool SetFieldValue(TEntity entity, string fieldName, Int32 value)
        {
            var setter = GetInt32FieldSetter(fieldName);
            if (setter != null)
            {
                setter(entity, value);
                return true;
            }

            return false;
        }

        public bool SetFieldValue(TEntity entity, string fieldName, UInt32 value)
        {
            var setter = GetUInt32FieldSetter(fieldName);
            if (setter != null)
            {
                setter(entity, value);
                return true;
            }

            return false;
        }

        public bool SetFieldValue(TEntity entity, string fieldName, Int64 value)
        {
            var setter = GetInt64FieldSetter(fieldName);
            if (setter != null)
            {
                setter(entity, value);
                return true;
            }

            return false;
        }

        public bool SetFieldValue(TEntity entity, string fieldName, UInt64 value)
        {
            var setter = GetUInt64FieldSetter(fieldName);
            if (setter != null)
            {
                setter(entity, value);
                return true;
            }

            return false;
        }

        public bool SetFieldValue(TEntity entity, string fieldName, Single value)
        {
            var setter = GetSingleFieldSetter(fieldName);
            if (setter != null)
            {
                setter(entity, value);
                return true;
            }

            return false;
        }

        public bool SetFieldValue(TEntity entity, string fieldName, Double value)
        {
            var setter = GetDoubleFieldSetter(fieldName);
            if (setter != null)
            {
                setter(entity, value);
                return true;
            }

            return false;
        }

        public bool SetFieldValue(TEntity entity, string fieldName, Decimal value)
        {
            var setter = GetDecimalFieldSetter(fieldName);
            if (setter != null)
            {
                setter(entity, value);
                return true;
            }

            return false;
        }

        public bool SetFieldValue(TEntity entity, string fieldName, DateTime value)
        {
            var setter = GetDateTimeFieldSetter(fieldName);
            if (setter != null)
            {
                setter(entity, value);
                return true;
            }

            return false;
        }

        public bool SetFieldValue(TEntity entity, string fieldName, String value)
        {
            var setter = GetStringFieldSetter(fieldName);
            if (setter != null)
            {
                setter(entity, value);
                return true;
            }

            return false;
        }

	}
}