//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by a tool. 
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------

namespace Catel.Reflection
{
    using System;
    using Catel.Data;

    public partial class FastMemberInvoker<TEntity>
    {
        public bool TryGetFieldValue(TEntity entity, string fieldName, out Object item) => 
            TryGetFieldValue<Object>((TEntity)entity, fieldName, out item);

        public bool TryGetFieldValue(TEntity entity, string fieldName, out Boolean item) => 
            TryGetFieldValue<Boolean>((TEntity)entity, fieldName, out item);

        public bool TryGetFieldValue(TEntity entity, string fieldName, out Char item) => 
            TryGetFieldValue<Char>((TEntity)entity, fieldName, out item);

        public bool TryGetFieldValue(TEntity entity, string fieldName, out SByte item) => 
            TryGetFieldValue<SByte>((TEntity)entity, fieldName, out item);

        public bool TryGetFieldValue(TEntity entity, string fieldName, out Byte item) => 
            TryGetFieldValue<Byte>((TEntity)entity, fieldName, out item);

        public bool TryGetFieldValue(TEntity entity, string fieldName, out Int16 item) => 
            TryGetFieldValue<Int16>((TEntity)entity, fieldName, out item);

        public bool TryGetFieldValue(TEntity entity, string fieldName, out UInt16 item) => 
            TryGetFieldValue<UInt16>((TEntity)entity, fieldName, out item);

        public bool TryGetFieldValue(TEntity entity, string fieldName, out Int32 item) => 
            TryGetFieldValue<Int32>((TEntity)entity, fieldName, out item);

        public bool TryGetFieldValue(TEntity entity, string fieldName, out UInt32 item) => 
            TryGetFieldValue<UInt32>((TEntity)entity, fieldName, out item);

        public bool TryGetFieldValue(TEntity entity, string fieldName, out Int64 item) => 
            TryGetFieldValue<Int64>((TEntity)entity, fieldName, out item);

        public bool TryGetFieldValue(TEntity entity, string fieldName, out UInt64 item) => 
            TryGetFieldValue<UInt64>((TEntity)entity, fieldName, out item);

        public bool TryGetFieldValue(TEntity entity, string fieldName, out Single item) => 
            TryGetFieldValue<Single>((TEntity)entity, fieldName, out item);

        public bool TryGetFieldValue(TEntity entity, string fieldName, out Double item) => 
            TryGetFieldValue<Double>((TEntity)entity, fieldName, out item);

        public bool TryGetFieldValue(TEntity entity, string fieldName, out Decimal item) => 
            TryGetFieldValue<Decimal>((TEntity)entity, fieldName, out item);

        public bool TryGetFieldValue(TEntity entity, string fieldName, out DateTime item) => 
            TryGetFieldValue<DateTime>((TEntity)entity, fieldName, out item);

        public bool TryGetFieldValue(TEntity entity, string fieldName, out String item) => 
            TryGetFieldValue<String>((TEntity)entity, fieldName, out item);

    }
}
