//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by a tool. 
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------

namespace Catel.Reflection
{
	using System;

	public partial class FastMemberInvoker<TEntity>
	{

        bool IFastMemberInvoker.TryGetPropertyValue(object entity, string propertyName, out Object item)
        {
            return TryGetPropertyValue((TEntity)entity, propertyName, out item);
        }

        bool IFastMemberInvoker.SetPropertyValue(object entity, string propertyName, Object item)
        {
            return SetPropertyValue((TEntity)entity, propertyName, item);
        }


        bool IFastMemberInvoker.TryGetPropertyValue(object entity, string propertyName, out Boolean item)
        {
            return TryGetPropertyValue((TEntity)entity, propertyName, out item);
        }

        bool IFastMemberInvoker.SetPropertyValue(object entity, string propertyName, Boolean item)
        {
            return SetPropertyValue((TEntity)entity, propertyName, item);
        }


        bool IFastMemberInvoker.TryGetPropertyValue(object entity, string propertyName, out Char item)
        {
            return TryGetPropertyValue((TEntity)entity, propertyName, out item);
        }

        bool IFastMemberInvoker.SetPropertyValue(object entity, string propertyName, Char item)
        {
            return SetPropertyValue((TEntity)entity, propertyName, item);
        }


        bool IFastMemberInvoker.TryGetPropertyValue(object entity, string propertyName, out SByte item)
        {
            return TryGetPropertyValue((TEntity)entity, propertyName, out item);
        }

        bool IFastMemberInvoker.SetPropertyValue(object entity, string propertyName, SByte item)
        {
            return SetPropertyValue((TEntity)entity, propertyName, item);
        }


        bool IFastMemberInvoker.TryGetPropertyValue(object entity, string propertyName, out Byte item)
        {
            return TryGetPropertyValue((TEntity)entity, propertyName, out item);
        }

        bool IFastMemberInvoker.SetPropertyValue(object entity, string propertyName, Byte item)
        {
            return SetPropertyValue((TEntity)entity, propertyName, item);
        }


        bool IFastMemberInvoker.TryGetPropertyValue(object entity, string propertyName, out Int16 item)
        {
            return TryGetPropertyValue((TEntity)entity, propertyName, out item);
        }

        bool IFastMemberInvoker.SetPropertyValue(object entity, string propertyName, Int16 item)
        {
            return SetPropertyValue((TEntity)entity, propertyName, item);
        }


        bool IFastMemberInvoker.TryGetPropertyValue(object entity, string propertyName, out UInt16 item)
        {
            return TryGetPropertyValue((TEntity)entity, propertyName, out item);
        }

        bool IFastMemberInvoker.SetPropertyValue(object entity, string propertyName, UInt16 item)
        {
            return SetPropertyValue((TEntity)entity, propertyName, item);
        }


        bool IFastMemberInvoker.TryGetPropertyValue(object entity, string propertyName, out Int32 item)
        {
            return TryGetPropertyValue((TEntity)entity, propertyName, out item);
        }

        bool IFastMemberInvoker.SetPropertyValue(object entity, string propertyName, Int32 item)
        {
            return SetPropertyValue((TEntity)entity, propertyName, item);
        }


        bool IFastMemberInvoker.TryGetPropertyValue(object entity, string propertyName, out UInt32 item)
        {
            return TryGetPropertyValue((TEntity)entity, propertyName, out item);
        }

        bool IFastMemberInvoker.SetPropertyValue(object entity, string propertyName, UInt32 item)
        {
            return SetPropertyValue((TEntity)entity, propertyName, item);
        }


        bool IFastMemberInvoker.TryGetPropertyValue(object entity, string propertyName, out Int64 item)
        {
            return TryGetPropertyValue((TEntity)entity, propertyName, out item);
        }

        bool IFastMemberInvoker.SetPropertyValue(object entity, string propertyName, Int64 item)
        {
            return SetPropertyValue((TEntity)entity, propertyName, item);
        }


        bool IFastMemberInvoker.TryGetPropertyValue(object entity, string propertyName, out UInt64 item)
        {
            return TryGetPropertyValue((TEntity)entity, propertyName, out item);
        }

        bool IFastMemberInvoker.SetPropertyValue(object entity, string propertyName, UInt64 item)
        {
            return SetPropertyValue((TEntity)entity, propertyName, item);
        }


        bool IFastMemberInvoker.TryGetPropertyValue(object entity, string propertyName, out Single item)
        {
            return TryGetPropertyValue((TEntity)entity, propertyName, out item);
        }

        bool IFastMemberInvoker.SetPropertyValue(object entity, string propertyName, Single item)
        {
            return SetPropertyValue((TEntity)entity, propertyName, item);
        }


        bool IFastMemberInvoker.TryGetPropertyValue(object entity, string propertyName, out Double item)
        {
            return TryGetPropertyValue((TEntity)entity, propertyName, out item);
        }

        bool IFastMemberInvoker.SetPropertyValue(object entity, string propertyName, Double item)
        {
            return SetPropertyValue((TEntity)entity, propertyName, item);
        }


        bool IFastMemberInvoker.TryGetPropertyValue(object entity, string propertyName, out Decimal item)
        {
            return TryGetPropertyValue((TEntity)entity, propertyName, out item);
        }

        bool IFastMemberInvoker.SetPropertyValue(object entity, string propertyName, Decimal item)
        {
            return SetPropertyValue((TEntity)entity, propertyName, item);
        }


        bool IFastMemberInvoker.TryGetPropertyValue(object entity, string propertyName, out DateTime item)
        {
            return TryGetPropertyValue((TEntity)entity, propertyName, out item);
        }

        bool IFastMemberInvoker.SetPropertyValue(object entity, string propertyName, DateTime item)
        {
            return SetPropertyValue((TEntity)entity, propertyName, item);
        }


        bool IFastMemberInvoker.TryGetPropertyValue(object entity, string propertyName, out String item)
        {
            return TryGetPropertyValue((TEntity)entity, propertyName, out item);
        }

        bool IFastMemberInvoker.SetPropertyValue(object entity, string propertyName, String item)
        {
            return SetPropertyValue((TEntity)entity, propertyName, item);
        }

	}
}