//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by a tool. 
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------

namespace Catel.Reflection
{
	using System;

	public partial class FastMemberInvoker<TEntity>
	{
		public bool TryGetPropertyValue(TEntity entity, string propertyName, out Object item)
		{
			if (_objectPropertyGettersCache.TryGetValue(propertyName, out Func<TEntity, Object> getter))
			{
				item = getter(entity);

				return true;
			}

			item = default;

			return false;
		}

		public bool TryGetPropertyValue(TEntity entity, string propertyName, out Boolean item)
		{
			if (_booleanPropertyGettersCache.TryGetValue(propertyName, out Func<TEntity, Boolean> getter))
			{
				item = getter(entity);

				return true;
			}

			item = default;

			return false;
		}

		public bool TryGetPropertyValue(TEntity entity, string propertyName, out Char item)
		{
			if (_charPropertyGettersCache.TryGetValue(propertyName, out Func<TEntity, Char> getter))
			{
				item = getter(entity);

				return true;
			}

			item = default;

			return false;
		}

		public bool TryGetPropertyValue(TEntity entity, string propertyName, out SByte item)
		{
			if (_sbytePropertyGettersCache.TryGetValue(propertyName, out Func<TEntity, SByte> getter))
			{
				item = getter(entity);

				return true;
			}

			item = default;

			return false;
		}

		public bool TryGetPropertyValue(TEntity entity, string propertyName, out Byte item)
		{
			if (_bytePropertyGettersCache.TryGetValue(propertyName, out Func<TEntity, Byte> getter))
			{
				item = getter(entity);

				return true;
			}

			item = default;

			return false;
		}

		public bool TryGetPropertyValue(TEntity entity, string propertyName, out Int16 item)
		{
			if (_int16PropertyGettersCache.TryGetValue(propertyName, out Func<TEntity, Int16> getter))
			{
				item = getter(entity);

				return true;
			}

			item = default;

			return false;
		}

		public bool TryGetPropertyValue(TEntity entity, string propertyName, out UInt16 item)
		{
			if (_uint16PropertyGettersCache.TryGetValue(propertyName, out Func<TEntity, UInt16> getter))
			{
				item = getter(entity);

				return true;
			}

			item = default;

			return false;
		}

		public bool TryGetPropertyValue(TEntity entity, string propertyName, out Int32 item)
		{
			if (_int32PropertyGettersCache.TryGetValue(propertyName, out Func<TEntity, Int32> getter))
			{
				item = getter(entity);

				return true;
			}

			item = default;

			return false;
		}

		public bool TryGetPropertyValue(TEntity entity, string propertyName, out UInt32 item)
		{
			if (_uint32PropertyGettersCache.TryGetValue(propertyName, out Func<TEntity, UInt32> getter))
			{
				item = getter(entity);

				return true;
			}

			item = default;

			return false;
		}

		public bool TryGetPropertyValue(TEntity entity, string propertyName, out Int64 item)
		{
			if (_int64PropertyGettersCache.TryGetValue(propertyName, out Func<TEntity, Int64> getter))
			{
				item = getter(entity);

				return true;
			}

			item = default;

			return false;
		}

		public bool TryGetPropertyValue(TEntity entity, string propertyName, out UInt64 item)
		{
			if (_uint64PropertyGettersCache.TryGetValue(propertyName, out Func<TEntity, UInt64> getter))
			{
				item = getter(entity);

				return true;
			}

			item = default;

			return false;
		}

		public bool TryGetPropertyValue(TEntity entity, string propertyName, out Single item)
		{
			if (_singlePropertyGettersCache.TryGetValue(propertyName, out Func<TEntity, Single> getter))
			{
				item = getter(entity);

				return true;
			}

			item = default;

			return false;
		}

		public bool TryGetPropertyValue(TEntity entity, string propertyName, out Double item)
		{
			if (_doublePropertyGettersCache.TryGetValue(propertyName, out Func<TEntity, Double> getter))
			{
				item = getter(entity);

				return true;
			}

			item = default;

			return false;
		}

		public bool TryGetPropertyValue(TEntity entity, string propertyName, out Decimal item)
		{
			if (_decimalPropertyGettersCache.TryGetValue(propertyName, out Func<TEntity, Decimal> getter))
			{
				item = getter(entity);

				return true;
			}

			item = default;

			return false;
		}

		public bool TryGetPropertyValue(TEntity entity, string propertyName, out DateTime item)
		{
			if (_datetimePropertyGettersCache.TryGetValue(propertyName, out Func<TEntity, DateTime> getter))
			{
				item = getter(entity);

				return true;
			}

			item = default;

			return false;
		}

		public bool TryGetPropertyValue(TEntity entity, string propertyName, out String item)
		{
			if (_stringPropertyGettersCache.TryGetValue(propertyName, out Func<TEntity, String> getter))
			{
				item = getter(entity);

				return true;
			}

			item = default;

			return false;
		}

	}
}