//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17020
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catel.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Exceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Exceptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Catel.WP7.Properties.Catel.Core.Exceptions", typeof(Exceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BeginEdit cannot be invoked twice. A call to BeginEdit must always be closed with a call to CancelEdit or EndEdit..
        /// </summary>
        internal static string BeginEditCannotBeInvokedTwice {
            get {
                return ResourceManager.GetString("BeginEditCannotBeInvokedTwice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot compare to other object because the other object does not implement IDataObjectBase.
        /// </summary>
        internal static string CannotCompareToObjectNotImplementingIDataObjectBase {
            get {
                return ResourceManager.GetString("CannotCompareToObjectNotImplementingIDataObjectBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get the value of property &apos;{0}&apos;.
        /// </summary>
        internal static string CannotGetPropertyValueException {
            get {
                return ResourceManager.GetString("CannotGetPropertyValueException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set the value of property &apos;{0}&apos;.
        /// </summary>
        internal static string CannotSetPropertyValueException {
            get {
                return ResourceManager.GetString("CannotSetPropertyValueException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create directory &apos;{0}&apos;.
        /// </summary>
        internal static string FailedToCreateDirectory {
            get {
                return ResourceManager.GetString("FailedToCreateDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or no view model.
        /// </summary>
        internal static string InvalidViewModel {
            get {
                return ResourceManager.GetString("InvalidViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no model &apos;{0}&apos; registered with the model attribute, so the ViewModelToModel attribute on property &apos;{1}&apos; is invalid.
        ///
        ///If you are sure that you have a model with this name, make sure it&apos;s public instead of private or protected for Silverlight and WP7 because non-public reflection is not allowed in Silverlight..
        /// </summary>
        internal static string ModelNotRegistered {
            get {
                return ResourceManager.GetString("ModelNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties that are not serializable are not supported.
        /// </summary>
        internal static string NonSerializablePropertiesNotSupported {
            get {
                return ResourceManager.GetString("NonSerializablePropertiesNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately, this is not supported in Silverlight.
        /// </summary>
        internal static string NotSupportedInSilverlight {
            get {
                return ResourceManager.GetString("NotSupportedInSilverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately, this is not supported in Windows Phone 7.
        /// </summary>
        internal static string NotSupportedInWindowsPhone7 {
            get {
                return ResourceManager.GetString("NotSupportedInWindowsPhone7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no page registered as &apos;{0}&apos;.
        /// </summary>
        internal static string PageNotRegistered {
            get {
                return ResourceManager.GetString("PageNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; is not found.
        /// </summary>
        internal static string PropertyNotFound {
            get {
                return ResourceManager.GetString("PropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapped viewmodel property &apos;{0}&apos; to model property &apos;{1}&apos; is invalid because property &apos;{1}&apos; is not found on the model &apos;{2}&apos;.
        /// </summary>
        internal static string PropertyNotFoundInModel {
            get {
                return ResourceManager.GetString("PropertyNotFoundInModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The view model of type &apos;{0}&apos; is not registered thus cannot be used in this context.
        /// </summary>
        internal static string ViewModelNotRegistered {
            get {
                return ResourceManager.GetString("ViewModelNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no window registered as &apos;{0}&apos;.
        /// </summary>
        internal static string WindowNotRegistered {
            get {
                return ResourceManager.GetString("WindowNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The view model is of the wrong type. Expected &apos;{0}&apos;, but type is &apos;{1}&apos;.
        /// </summary>
        internal static string WrongViewModelType {
            get {
                return ResourceManager.GetString("WrongViewModelType", resourceCulture);
            }
        }
    }
}
