
//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by a tool. 
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------

namespace Catel.Data
{
    using System;

    public partial class PropertyBag
    {
        private static readonly BoxingCache<Boolean> BooleanBoxingCache = new BoxingCache<Boolean>();

        /// <summary>
        /// Sets the property value.
        /// </summary>
        /// <param name="propertyName">Name of the property.</param>
        /// <param name="value">The value.</param>
        /// <exception cref="ArgumentException">The <paramref name="propertyName" /> is <c>null</c> or whitespace.</exception>
        public void SetValue(string propertyName, Boolean value)
        {
            var boxedValue = BooleanBoxingCache.GetBoxedValue(value);
            SetValue<object>(propertyName, boxedValue);
        }

        private static readonly BoxingCache<Char> CharBoxingCache = new BoxingCache<Char>();

        /// <summary>
        /// Sets the property value.
        /// </summary>
        /// <param name="propertyName">Name of the property.</param>
        /// <param name="value">The value.</param>
        /// <exception cref="ArgumentException">The <paramref name="propertyName" /> is <c>null</c> or whitespace.</exception>
        public void SetValue(string propertyName, Char value)
        {
            var boxedValue = CharBoxingCache.GetBoxedValue(value);
            SetValue<object>(propertyName, boxedValue);
        }

        private static readonly BoxingCache<SByte> SByteBoxingCache = new BoxingCache<SByte>();

        /// <summary>
        /// Sets the property value.
        /// </summary>
        /// <param name="propertyName">Name of the property.</param>
        /// <param name="value">The value.</param>
        /// <exception cref="ArgumentException">The <paramref name="propertyName" /> is <c>null</c> or whitespace.</exception>
        public void SetValue(string propertyName, SByte value)
        {
            var boxedValue = SByteBoxingCache.GetBoxedValue(value);
            SetValue<object>(propertyName, boxedValue);
        }

        private static readonly BoxingCache<Byte> ByteBoxingCache = new BoxingCache<Byte>();

        /// <summary>
        /// Sets the property value.
        /// </summary>
        /// <param name="propertyName">Name of the property.</param>
        /// <param name="value">The value.</param>
        /// <exception cref="ArgumentException">The <paramref name="propertyName" /> is <c>null</c> or whitespace.</exception>
        public void SetValue(string propertyName, Byte value)
        {
            var boxedValue = ByteBoxingCache.GetBoxedValue(value);
            SetValue<object>(propertyName, boxedValue);
        }

        private static readonly BoxingCache<Int16> Int16BoxingCache = new BoxingCache<Int16>();

        /// <summary>
        /// Sets the property value.
        /// </summary>
        /// <param name="propertyName">Name of the property.</param>
        /// <param name="value">The value.</param>
        /// <exception cref="ArgumentException">The <paramref name="propertyName" /> is <c>null</c> or whitespace.</exception>
        public void SetValue(string propertyName, Int16 value)
        {
            var boxedValue = Int16BoxingCache.GetBoxedValue(value);
            SetValue<object>(propertyName, boxedValue);
        }

        private static readonly BoxingCache<UInt16> UInt16BoxingCache = new BoxingCache<UInt16>();

        /// <summary>
        /// Sets the property value.
        /// </summary>
        /// <param name="propertyName">Name of the property.</param>
        /// <param name="value">The value.</param>
        /// <exception cref="ArgumentException">The <paramref name="propertyName" /> is <c>null</c> or whitespace.</exception>
        public void SetValue(string propertyName, UInt16 value)
        {
            var boxedValue = UInt16BoxingCache.GetBoxedValue(value);
            SetValue<object>(propertyName, boxedValue);
        }

        private static readonly BoxingCache<Int32> Int32BoxingCache = new BoxingCache<Int32>();

        /// <summary>
        /// Sets the property value.
        /// </summary>
        /// <param name="propertyName">Name of the property.</param>
        /// <param name="value">The value.</param>
        /// <exception cref="ArgumentException">The <paramref name="propertyName" /> is <c>null</c> or whitespace.</exception>
        public void SetValue(string propertyName, Int32 value)
        {
            var boxedValue = Int32BoxingCache.GetBoxedValue(value);
            SetValue<object>(propertyName, boxedValue);
        }

        private static readonly BoxingCache<UInt32> UInt32BoxingCache = new BoxingCache<UInt32>();

        /// <summary>
        /// Sets the property value.
        /// </summary>
        /// <param name="propertyName">Name of the property.</param>
        /// <param name="value">The value.</param>
        /// <exception cref="ArgumentException">The <paramref name="propertyName" /> is <c>null</c> or whitespace.</exception>
        public void SetValue(string propertyName, UInt32 value)
        {
            var boxedValue = UInt32BoxingCache.GetBoxedValue(value);
            SetValue<object>(propertyName, boxedValue);
        }

        private static readonly BoxingCache<Int64> Int64BoxingCache = new BoxingCache<Int64>();

        /// <summary>
        /// Sets the property value.
        /// </summary>
        /// <param name="propertyName">Name of the property.</param>
        /// <param name="value">The value.</param>
        /// <exception cref="ArgumentException">The <paramref name="propertyName" /> is <c>null</c> or whitespace.</exception>
        public void SetValue(string propertyName, Int64 value)
        {
            var boxedValue = Int64BoxingCache.GetBoxedValue(value);
            SetValue<object>(propertyName, boxedValue);
        }

        private static readonly BoxingCache<UInt64> UInt64BoxingCache = new BoxingCache<UInt64>();

        /// <summary>
        /// Sets the property value.
        /// </summary>
        /// <param name="propertyName">Name of the property.</param>
        /// <param name="value">The value.</param>
        /// <exception cref="ArgumentException">The <paramref name="propertyName" /> is <c>null</c> or whitespace.</exception>
        public void SetValue(string propertyName, UInt64 value)
        {
            var boxedValue = UInt64BoxingCache.GetBoxedValue(value);
            SetValue<object>(propertyName, boxedValue);
        }

        private static readonly BoxingCache<Single> SingleBoxingCache = new BoxingCache<Single>();

        /// <summary>
        /// Sets the property value.
        /// </summary>
        /// <param name="propertyName">Name of the property.</param>
        /// <param name="value">The value.</param>
        /// <exception cref="ArgumentException">The <paramref name="propertyName" /> is <c>null</c> or whitespace.</exception>
        public void SetValue(string propertyName, Single value)
        {
            var boxedValue = SingleBoxingCache.GetBoxedValue(value);
            SetValue<object>(propertyName, boxedValue);
        }

        private static readonly BoxingCache<Double> DoubleBoxingCache = new BoxingCache<Double>();

        /// <summary>
        /// Sets the property value.
        /// </summary>
        /// <param name="propertyName">Name of the property.</param>
        /// <param name="value">The value.</param>
        /// <exception cref="ArgumentException">The <paramref name="propertyName" /> is <c>null</c> or whitespace.</exception>
        public void SetValue(string propertyName, Double value)
        {
            var boxedValue = DoubleBoxingCache.GetBoxedValue(value);
            SetValue<object>(propertyName, boxedValue);
        }

        private static readonly BoxingCache<Decimal> DecimalBoxingCache = new BoxingCache<Decimal>();

        /// <summary>
        /// Sets the property value.
        /// </summary>
        /// <param name="propertyName">Name of the property.</param>
        /// <param name="value">The value.</param>
        /// <exception cref="ArgumentException">The <paramref name="propertyName" /> is <c>null</c> or whitespace.</exception>
        public void SetValue(string propertyName, Decimal value)
        {
            var boxedValue = DecimalBoxingCache.GetBoxedValue(value);
            SetValue<object>(propertyName, boxedValue);
        }

        private static readonly BoxingCache<DateTime> DateTimeBoxingCache = new BoxingCache<DateTime>();

        /// <summary>
        /// Sets the property value.
        /// </summary>
        /// <param name="propertyName">Name of the property.</param>
        /// <param name="value">The value.</param>
        /// <exception cref="ArgumentException">The <paramref name="propertyName" /> is <c>null</c> or whitespace.</exception>
        public void SetValue(string propertyName, DateTime value)
        {
            var boxedValue = DateTimeBoxingCache.GetBoxedValue(value);
            SetValue<object>(propertyName, boxedValue);
        }

        private static readonly BoxingCache<String> StringBoxingCache = new BoxingCache<String>();

        /// <summary>
        /// Sets the property value.
        /// </summary>
        /// <param name="propertyName">Name of the property.</param>
        /// <param name="value">The value.</param>
        /// <exception cref="ArgumentException">The <paramref name="propertyName" /> is <c>null</c> or whitespace.</exception>
        public void SetValue(string propertyName, String value)
        {
            var boxedValue = StringBoxingCache.GetBoxedValue(value);
            SetValue<object>(propertyName, boxedValue);
        }

    }
}      