//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catel.MVVM.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Exceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Exceptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Catel.Properties.Exceptions", typeof(Exceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be of type Window.
        /// </summary>
        internal static string ArgumentMustBeOfTypeWindow {
            get {
                return ResourceManager.GetString("ArgumentMustBeOfTypeWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument must implement IViewModel interface.
        /// </summary>
        internal static string ArgumentMustImplementIViewModelInterface {
            get {
                return ResourceManager.GetString("ArgumentMustImplementIViewModelInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control template must contain part &apos;{0}&apos;.
        /// </summary>
        internal static string ControlTemplateMustContainPart {
            get {
                return ResourceManager.GetString("ControlTemplateMustContainPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataWindowButtons can only be added when the window is not yet loaded.
        /// </summary>
        internal static string DataWindowButtonCanOnlyBeAddedWhenWindowIsNotLoaded {
            get {
                return ResourceManager.GetString("DataWindowButtonCanOnlyBeAddedWhenWindowIsNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to configure IoC container.
        /// </summary>
        internal static string FailedToConfigureIoCContainer {
            get {
                return ResourceManager.GetString("FailedToConfigureIoCContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or no view model.
        /// </summary>
        internal static string InvalidViewModel {
            get {
                return ResourceManager.GetString("InvalidViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no model &apos;{0}&apos; registered with the model attribute, so the ViewModelToModel attribute on property &apos;{1}&apos; is invalid.
        ///
        ///Make sure that the property is a Catel property, not a regular property.
        ///
        ///If you are sure that you have a model with this name, make sure it&apos;s public instead of private or protected for Silverlight and WP7 because non-public reflection is not allowed in Silverlight..
        /// </summary>
        internal static string ModelNotRegistered {
            get {
                return ResourceManager.GetString("ModelNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No expected results in the queue, set up expected result first.
        /// </summary>
        internal static string NoExpectedResultsInQueueForUnitTest {
            get {
                return ResourceManager.GetString("NoExpectedResultsInQueueForUnitTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no page registered as &apos;{0}&apos;.
        /// </summary>
        internal static string PageNotRegistered {
            get {
                return ResourceManager.GetString("PageNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapped viewmodel property &apos;{0}&apos; to model property &apos;{1}&apos; is invalid because property &apos;{1}&apos; is not found on the model &apos;{2}&apos;&lt;/value&gt;
        ///    &lt;comment&gt;{0} = view model property name
        ///{1} = model property name
        ///{2} = model name.
        /// </summary>
        internal static string PropertyNotFoundInModel {
            get {
                return ResourceManager.GetString("PropertyNotFoundInModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View model already registered.
        /// </summary>
        internal static string ViewModelAlreadyRegistered {
            get {
                return ResourceManager.GetString("ViewModelAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The viewModelContainer must be of type DependencyObject.
        /// </summary>
        internal static string ViewModelContainerMustBeOfTypeDependencyObject {
            get {
                return ResourceManager.GetString("ViewModelContainerMustBeOfTypeDependencyObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The view model of type &apos;{0}&apos; is not registered thus cannot be used in this context.
        /// </summary>
        internal static string ViewModelNotRegistered {
            get {
                return ResourceManager.GetString("ViewModelNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibility.Visible is not possible as not-visible option.
        /// </summary>
        internal static string VisibilityIsNotAllowedForConverter {
            get {
                return ResourceManager.GetString("VisibilityIsNotAllowedForConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no window registered as &apos;{0}&apos;.
        /// </summary>
        internal static string WindowNotRegistered {
            get {
                return ResourceManager.GetString("WindowNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The view model is of the wrong type. Expected &apos;{0}&apos;, but type is &apos;{1}&apos;.
        /// </summary>
        internal static string WrongViewModelType {
            get {
                return ResourceManager.GetString("WrongViewModelType", resourceCulture);
            }
        }
    }
}
