//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by a tool. 
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------

namespace Catel.Reflection
{
	using System;

	public partial interface IFastMemberInvoker
	{
        bool TryGetFieldValue(object entity, string fieldName, out Object item);
        bool SetFieldValue(object entity, string fieldName, Object item);

        bool TryGetPropertyValue(object entity, string propertyName, out Object item);
        bool SetPropertyValue(object entity, string propertyName, Object item);

        bool TryGetFieldValue(object entity, string fieldName, out Boolean item);
        bool SetFieldValue(object entity, string fieldName, Boolean item);

        bool TryGetPropertyValue(object entity, string propertyName, out Boolean item);
        bool SetPropertyValue(object entity, string propertyName, Boolean item);

        bool TryGetFieldValue(object entity, string fieldName, out Char item);
        bool SetFieldValue(object entity, string fieldName, Char item);

        bool TryGetPropertyValue(object entity, string propertyName, out Char item);
        bool SetPropertyValue(object entity, string propertyName, Char item);

        bool TryGetFieldValue(object entity, string fieldName, out SByte item);
        bool SetFieldValue(object entity, string fieldName, SByte item);

        bool TryGetPropertyValue(object entity, string propertyName, out SByte item);
        bool SetPropertyValue(object entity, string propertyName, SByte item);

        bool TryGetFieldValue(object entity, string fieldName, out Byte item);
        bool SetFieldValue(object entity, string fieldName, Byte item);

        bool TryGetPropertyValue(object entity, string propertyName, out Byte item);
        bool SetPropertyValue(object entity, string propertyName, Byte item);

        bool TryGetFieldValue(object entity, string fieldName, out Int16 item);
        bool SetFieldValue(object entity, string fieldName, Int16 item);

        bool TryGetPropertyValue(object entity, string propertyName, out Int16 item);
        bool SetPropertyValue(object entity, string propertyName, Int16 item);

        bool TryGetFieldValue(object entity, string fieldName, out UInt16 item);
        bool SetFieldValue(object entity, string fieldName, UInt16 item);

        bool TryGetPropertyValue(object entity, string propertyName, out UInt16 item);
        bool SetPropertyValue(object entity, string propertyName, UInt16 item);

        bool TryGetFieldValue(object entity, string fieldName, out Int32 item);
        bool SetFieldValue(object entity, string fieldName, Int32 item);

        bool TryGetPropertyValue(object entity, string propertyName, out Int32 item);
        bool SetPropertyValue(object entity, string propertyName, Int32 item);

        bool TryGetFieldValue(object entity, string fieldName, out UInt32 item);
        bool SetFieldValue(object entity, string fieldName, UInt32 item);

        bool TryGetPropertyValue(object entity, string propertyName, out UInt32 item);
        bool SetPropertyValue(object entity, string propertyName, UInt32 item);

        bool TryGetFieldValue(object entity, string fieldName, out Int64 item);
        bool SetFieldValue(object entity, string fieldName, Int64 item);

        bool TryGetPropertyValue(object entity, string propertyName, out Int64 item);
        bool SetPropertyValue(object entity, string propertyName, Int64 item);

        bool TryGetFieldValue(object entity, string fieldName, out UInt64 item);
        bool SetFieldValue(object entity, string fieldName, UInt64 item);

        bool TryGetPropertyValue(object entity, string propertyName, out UInt64 item);
        bool SetPropertyValue(object entity, string propertyName, UInt64 item);

        bool TryGetFieldValue(object entity, string fieldName, out Single item);
        bool SetFieldValue(object entity, string fieldName, Single item);

        bool TryGetPropertyValue(object entity, string propertyName, out Single item);
        bool SetPropertyValue(object entity, string propertyName, Single item);

        bool TryGetFieldValue(object entity, string fieldName, out Double item);
        bool SetFieldValue(object entity, string fieldName, Double item);

        bool TryGetPropertyValue(object entity, string propertyName, out Double item);
        bool SetPropertyValue(object entity, string propertyName, Double item);

        bool TryGetFieldValue(object entity, string fieldName, out Decimal item);
        bool SetFieldValue(object entity, string fieldName, Decimal item);

        bool TryGetPropertyValue(object entity, string propertyName, out Decimal item);
        bool SetPropertyValue(object entity, string propertyName, Decimal item);

        bool TryGetFieldValue(object entity, string fieldName, out DateTime item);
        bool SetFieldValue(object entity, string fieldName, DateTime item);

        bool TryGetPropertyValue(object entity, string propertyName, out DateTime item);
        bool SetPropertyValue(object entity, string propertyName, DateTime item);

        bool TryGetFieldValue(object entity, string fieldName, out String item);
        bool SetFieldValue(object entity, string fieldName, String item);

        bool TryGetPropertyValue(object entity, string propertyName, out String item);
        bool SetPropertyValue(object entity, string propertyName, String item);

	}
}