//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catel.Test.EntityFramework5.DbContextTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbContextOrder
    {
        public int ProductId { get; set; }
        public int CustomerId { get; set; }
        public System.DateTime OrderCreated { get; set; }
        public int Amount { get; set; }
    
        public virtual DbContextCustomer DbContextCustomer { get; set; }
        public virtual DbContextProduct DbContextProduct { get; set; }
    }
}
