//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catel.Test.EntityFramework5.DbContextTest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestDbContextContainer : DbContext
    {
        public TestDbContextContainer()
            : base("name=TestDbContextContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DbContextCustomer> DbContextCustomers { get; set; }
        public DbSet<DbContextOrder> DbContextOrders { get; set; }
        public DbSet<DbContextProduct> DbContextProducts { get; set; }
    }
}
