name: Build and Publish DocFX

permissions:
  contents: write      # required to push to gh-pages
  
on:
  # Automatically 
  push:
    branches: [ develop ]
    paths:
      - 'doc/docfx/**'
  
  # Allow to run manually
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # 6.0.3

    - name: Install DocFX
      run: dotnet tool install -g docfx

    - name: Build documentation
      working-directory: doc/docfx
      run: docfx build
      
    - name: Add CNAME to output
      run: cp doc/docfx/CNAME doc/site/CNAME

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # 4.1.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: doc/site
        publish_branch: gh-pages
